#! /bin/bash

sudo ifconfig wlp2s0 down

if [[ $# -eq 0 || $1 == home ]]; then
  sudo ifconfig wlp2s0 up
  sudo wpa_supplicant -Dwext -iwlp2s0 -c/home/shionn/.wpa/AF32.conf -B
  sudo dhclient wlp2s0
elif [[ $1 == mb ]]; then
  sudo ifconfig wlp2s0 up
  sudo wpa_supplicant -Dwext -iwlp2s0 -c/home/shionn/.wpa/MB.conf -B
  sudo dhclient wlp2s0
elif [[ $1 == s4 ]]; then
  sudo ifconfig wlp2s0 up
  sudo wpa_supplicant -Dwext -iwlp2s0 -c/home/shionn/.wpa/S4.conf -B
  sudo dhclient wlp2s0
fi

echo done
